# Generated by Django 2.2.11 on 2020-03-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Original_Image', models.ImageField(upload_to='', verbose_name='Original_Image')),
                ('QR_Embedded_Image', models.ImageField(upload_to='', verbose_name='QR_Embedded_Image')),
            ],
        ),
    ]
