# Generated by Django 2.2.11 on 2020-03-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reality_Verifier_App', '0002_auto_20200316_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='QR_Embedded_Image',
        ),
        migrations.AlterField(
            model_name='picture',
            name='Original_Image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
