# Generated by Django 2.2.11 on 2020-03-22 09:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Reality_Verifier_App', '0003_auto_20200322_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='QR_Embedded_Image',
            field=models.ImageField(default=datetime.datetime(2020, 3, 22, 9, 32, 55, 728549, tzinfo=utc), upload_to='', verbose_name='QR_Embedded_Image'),
            preserve_default=False,
        ),
    ]
