# Generated by Django 2.2.11 on 2020-03-31 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reality_Verifier_App', '0004_picture_qr_embedded_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='QR_Embedded_Image',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='image_url',
        ),
    ]
