# Generated by Django 2.2.11 on 2020-04-08 03:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Reality_Verifier_App', '0005_auto_20200331_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='QR_Embedded_Image',
            field=models.ImageField(default=datetime.datetime(2020, 4, 8, 3, 37, 10, 193836, tzinfo=utc), upload_to='', verbose_name='QR_Embedded_Image'),
            preserve_default=False,
        ),
    ]
