# Generated by Django 2.2.11 on 2020-04-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reality_Verifier_App', '0006_picture_qr_embedded_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureQR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QR_Embedded_Image', models.ImageField(upload_to='', verbose_name='QR_Embedded_Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='picture',
            name='QR_Embedded_Image',
        ),
    ]
