# Generated by Django 2.2.11 on 2020-04-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reality_Verifier_App', '0007_auto_20200408_0459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PictureQR',
        ),
        migrations.AddField(
            model_name='picture',
            name='QR_Embedded_Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='picture',
            name='Original_Image',
            field=models.ImageField(upload_to='', verbose_name=''),
        ),
    ]
