# Generated by Django 2.2.11 on 2020-04-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reality_Verifier_App', '0008_auto_20200410_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='Original_Image',
            field=models.ImageField(upload_to='Original_Image'),
        ),
    ]
