# Generated by Django 2.2.11 on 2020-05-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reality_Verifier_App', '0012_auto_20200515_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='images',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='title',
        ),
    ]
